2024-06-13 15:53:55,626 [INFO]  starting up 24-06-13-1553_P1-test at 1.9580062499735504
2024-06-13 15:53:55,647 [INFO]  git SHA: 0ae36dcce70ead316e2748c3c0b3d4f7728b0675
2024-06-13 15:53:55,647 [INFO]  Configuration file: config/m2/1.json
2024-06-13 15:53:55,648 [INFO]  parameters {'reward_info': {'-4': {'desc': 'pattern_1', 'image': 'images[0]'}, '-3': {'desc': 'pattern_2', 'image': 'images[1]'}, '-2': {'desc': 'pattern_3', 'image': 'images[2]'}, '-1': {'desc': 'pattern_4', 'image': 'images[3]'}, '0': {'desc': 'pattern_5', 'image': 'images[4]'}, '1': {'desc': 'pattern_6', 'image': 'images[5]'}, '2': {'desc': 'pattern_7', 'image': 'images[6]'}, '3': {'desc': 'pattern_8', 'image': 'images[7]'}, '4': {'desc': 'pattern_9', 'image': 'images[8]'}}, 'images': ['pattern_1.png', 'pattern_2.png', 'pattern_3.png', 'pattern_4.png', 'pattern_5.png', 'pattern_6.png', 'pattern_7.png', 'pattern_8.png', 'pattern_9.png'], 'points_per_cent': 1, 'revealed': True, 'layout': [[0.0, 0.5], [-0.2938926261462365, 0.4045084971874737], [-0.47552825814757677, 0.15450849718747373], [-0.4755282581475768, -0.15450849718747361], [-0.2938926261462366, -0.40450849718747367], [-1.1102230246251565e-16, -0.5], [0.29389262614623646, -0.4045084971874738], [0.4755282581475768, -0.15450849718747384], [0.4755282581475768, 0.15450849718747361], [0.2938926261462367, 0.4045084971874736]]}
2024-06-13 15:53:56,807 [INFO]  begin intro
2024-06-13 15:53:56,807 [DEBUG]  message: Welcome! (None)
2024-06-13 15:53:57,382 [ERROR]  Expected a list of dictionaries for trial_set.
2024-06-13 15:53:57,382 [ERROR]  Caught exception in stage intro
Traceback (most recent call last):
  File "/Users/labadmin/twostep-eyetracking/experiment.py", line 36, in wrapper
    f(self, *args, **kwargs)
  File "/Users/labadmin/twostep-eyetracking/experiment.py", line 249, in intro
    gt.show()
AttributeError: 'NoneType' object has no attribute 'show'
